// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHqmHcmyNM06LDy4gN3MfkWYnibguHuX4',
    appId: '1:430363987997:web:5edb92cdebd3981785b6f4',
    messagingSenderId: '430363987997',
    projectId: 'netflix-clone-test-c1ca2',
    authDomain: 'netflix-clone-test-c1ca2.firebaseapp.com',
    storageBucket: 'netflix-clone-test-c1ca2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Af-eVPAm-l2UaNnMz9J1DKYIGaQN6aE',
    appId: '1:430363987997:android:23fc0e32ad99fc2785b6f4',
    messagingSenderId: '430363987997',
    projectId: 'netflix-clone-test-c1ca2',
    storageBucket: 'netflix-clone-test-c1ca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4gm4pTMkhFTSrM09YKKrfvt6szDn_eXA',
    appId: '1:430363987997:ios:cab6b33380aeb1a485b6f4',
    messagingSenderId: '430363987997',
    projectId: 'netflix-clone-test-c1ca2',
    storageBucket: 'netflix-clone-test-c1ca2.appspot.com',
    iosBundleId: 'com.example.cloneNetflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4gm4pTMkhFTSrM09YKKrfvt6szDn_eXA',
    appId: '1:430363987997:ios:43579fd24d25f95785b6f4',
    messagingSenderId: '430363987997',
    projectId: 'netflix-clone-test-c1ca2',
    storageBucket: 'netflix-clone-test-c1ca2.appspot.com',
    iosBundleId: 'com.example.cloneNetflix.RunnerTests',
  );
}
